### ISSUE TITLE
[Question] Make addon for Retail

### ISSUE THREAD

**Issue by echevarriandre** [Fibbles/whodis#1]
Is there any plans to port the addon to retail??

**Comment by Fibbles** [comment]
Hi. I don't play retail so I don't have much motivation to port the addon tbh. If it was just a case of changing a few lines I wouldn't mind too much. However, last time I looked into it the Interface Options menu was different in retail and the tooltip API had been completely rewritten. This would essentially mean mainting two different GUIs for the addon. I don't mind reviewing pull requests if someone else wants to maintain and test it though.
